use pkg_management;

CREATE TABLE TBL_CUSTOMER (
    CUSTOMER_ID INT CHECK ( CUSTOMER_ID < 10000 AND CUSTOMER_ID > 100 ) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(255),
    ANNUAL_REVENUE DECIMAL(10, 2),
    CUSTOMER_TYPE ENUM ('MANUFACTURER',  'WHOLESALER', 'RETAILER')
);

CREATE TABLE TBL_TRUCK_INFO (
    TRUCK_NO VARCHAR(255) PRIMARY KEY,
    DRIVER_NAME VARCHAR(255)

);

CREATE TABLE TBL_CITY (
    CITY_NAME VARCHAR(255) PRIMARY KEY,
    CITY_POPULATION INT

);

CREATE TABLE TBL_SHIPMENT_DETAILS (
    SHIPMENT_NO INT PRIMARY KEY,
    CUSTOMER_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES TBL_CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE,
    WEIGHT DECIMAL(10, 2) CHECK ( WEIGHT > 0 AND WEIGHT < 1000 ),
    TRUCK_NO VARCHAR(255),
    FOREIGN KEY (TRUCK_NO) REFERENCES TBL_TRUCK_INFO(TRUCK_NO) ON DELETE SET NULL,
    DESTINATION_CITY VARCHAR(255),
    SHIPPING_DATE DATE

);

-- INSERT 20 RECORDS INTO TBL_CUSTOMER



